# Site settings
title: Fengyang Wang
email: fengyang.wang@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  I’m Fengyang Wang, a mathematics student at the University of Waterloo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wafy.me" # the base hostname & protocol for your site
twitter_username: fengyang97
github_username:  TotalVerb

# Build settings
markdown: kramdown
